set -x
multi_files=(
/nlp_group/liupeng15/code/querysim/src/corpus_process/export/data.csharp128k_data_ratio1_complete.merge/Book__OpenSource_pile_Books3
/nlp_group/liupeng15/code/querysim/src/corpus_process/export/data.csharp128k_data_ratio1_complete.merge/Book__OpenSource_pile_BookCorpus2
/nlp_group/liupeng15/code/querysim/src/corpus_process/export/data.csharp128k_data_ratio1_complete.merge/Book__OpenSource_pile_Gutenberg
/nlp_group/liupeng15/code/querysim/src/corpus_process/export/data.csharp128k_data_ratio1_complete.merge/Book__DATA_zlib
/nlp_group/liupeng15/code/querysim/src/corpus_process/export/data.csharp128k_data_ratio1_complete.merge/Book__DATA_cbook
/nlp_group/liupeng15/code/querysim/src/corpus_process/export/data.csharp128k_data_ratio1_complete.merge/Book__DATA_weixin_dushu
/nlp_group/liupeng15/code/querysim/src/corpus_process/export/data.csharp128k_data_ratio1_complete.merge/Book__DATA_biqu_ge
/nlp_group/liupeng15/code/querysim/src/corpus_process/export/data.csharp128k_data_ratio1_complete.merge/Book__DATA_epubs
/nlp_group/liupeng15/code/querysim/src/corpus_process/export/data.csharp128k_data_ratio1_complete.merge/Baike__DATA_wiki__zh
/nlp_group/liupeng15/code/querysim/src/corpus_process/export/data.csharp128k_data_ratio1_complete.merge/Baike__DATA_wiki__en
/nlp_group/liupeng15/code/querysim/src/corpus_process/export/data.csharp128k_data_ratio1_complete.merge/Baike__DATA_baidu_baike
/nlp_group/liupeng15/code/querysim/src/corpus_process/export/data.csharp128k_data_ratio1_complete.merge/News__DATA_chinese_news
/nlp_group/liupeng15/code/querysim/src/corpus_process/export/data.csharp128k_data_ratio1_complete.merge/News__SELF_CC_NEWS
/nlp_group/liupeng15/code/querysim/src/corpus_process/export/data.csharp128k_data_ratio1_complete.merge/CC__SELF_CC__en
/nlp_group/liupeng15/code/querysim/src/corpus_process/export/data.csharp128k_data_ratio1_complete.merge/CC__SELF_CC_ALL__zh
/nlp_group/liupeng15/code/querysim/src/corpus_process/export/data.csharp128k_data_ratio1_complete.merge/WebText__DATA_webtext__zh
/nlp_group/liupeng15/code/querysim/src/corpus_process/export/data.csharp128k_data_ratio1_complete.merge/WebText__DATA_webtext__en
/nlp_group/liupeng15/code/querysim/src/corpus_process/export/data.csharp128k_data_ratio1_complete.merge/QA__SELF_stackexchange
/nlp_group/liupeng15/code/querysim/src/corpus_process/export/data.csharp128k_data_ratio1_complete.merge/QA__DATA_zhihu_qa
/nlp_group/liupeng15/code/querysim/src/corpus_process/export/data.csharp128k_data_ratio1_complete.merge/QA__DATA_baidu_zhidao
/nlp_group/liupeng15/code/querysim/src/corpus_process/export/data.csharp128k_data_ratio1_complete.merge/QA__DATA_baidu_jingyan
/nlp_group/liupeng15/code/querysim/src/corpus_process/export/data.csharp128k_data_ratio1_complete.merge/QA__DATA_zhihu_wenzhang
/nlp_group/liupeng15/code/querysim/src/corpus_process/export/data.csharp128k_data_ratio1_complete.merge/Academic__DATA_baidu_xueshu__zh
/nlp_group/liupeng15/code/querysim/src/corpus_process/export/data.csharp128k_data_ratio1_complete.merge/Academic__DATA_baidu_xueshu__en
/nlp_group/liupeng15/code/querysim/src/corpus_process/export/data.csharp128k_data_ratio1_complete.merge/Code__DATA_leetcode
/nlp_group/liupeng15/code/querysim/src/corpus_process/export/data.csharp128k_data_ratio1_complete.merge/Domain__DATA_lyric
/nlp_group/liupeng15/code/querysim/src/corpus_process/export/data.csharp128k_data_ratio1_complete.merge/Domain__OpenSource_pile_PhilPapers
/nlp_group/liupeng15/code/querysim/src/corpus_process/export/data.csharp128k_data_ratio1_complete.merge/Domain__OpenSource_pile_FreeLaw
/nlp_group/liupeng15/code/querysim/src/corpus_process/export/data.csharp128k_data_ratio1_complete.merge/Domain__OpenSource_pile_DMMathematics
/nlp_group/liupeng15/code/querysim/src/corpus_process/export/data.csharp128k_data_ratio1_complete.merge/Domain__OpenSource_pile_USPTOBackgrounds
/nlp_group/liupeng15/code/querysim/src/corpus_process/export/data.csharp128k_data_ratio1_complete.merge/Domain__OpenSource_pile_OpenSubtitles
/nlp_group/liupeng15/code/querysim/src/corpus_process/export/data.csharp128k_data_ratio1_complete.merge/Domain__OpenSource_pile_NIHExPorter
/nlp_group/liupeng15/code/querysim/src/corpus_process/export/data.csharp128k_data_ratio1_complete.merge/Academic__OpenSource_pile_PubMedAbstracts
/nlp_group/liupeng15/code/querysim/src/corpus_process/export/data.csharp128k_data_ratio1_complete.merge/Domain__DATA_weixin_gongzhonghao
/nlp_group/liupeng15/code/querysim/src/corpus_process/export/data.csharp128k_data_ratio1_complete.merge/Domain__DATA_china_baogao_dating
/nlp_group/liupeng15/code/querysim/src/corpus_process/export/data.csharp128k_data_ratio1_complete.merge/Domain__DATA_1999IT
/nlp_group/liupeng15/code/querysim/src/corpus_process/export/data.csharp128k_data_ratio1_complete.merge/Domain__DATA_yi_ou_zhi_ku
/nlp_group/liupeng15/code/querysim/src/corpus_process/export/data.csharp128k_data_ratio1_complete.merge/Domain__DATA_airuiwang
/nlp_group/liupeng15/code/querysim/src/corpus_process/export/data.csharp128k_data_ratio1_complete.merge/Domain__DATA_36kr
/nlp_group/liupeng15/code/querysim/src/corpus_process/export/data.csharp128k_data_ratio1_complete.merge/Domain__DATA_dongfang_caifu
/nlp_group/liupeng15/code/querysim/src/corpus_process/export/data.csharp128k_data_ratio1_complete.merge/Domain__DATA_xiao_hong_shu
/nlp_group/liupeng15/code/querysim/src/corpus_process/export/data.csharp128k_data_ratio1_complete.merge/Domain__DATA_dazhong_dianping
/nlp_group/liupeng15/code/querysim/src/corpus_process/export/data.csharp128k_data_ratio1_complete.merge/Domain__Github_gushi
/nlp_group/liupeng15/code/querysim/src/corpus_process/export/data.csharp128k_data_ratio1_complete.merge/Domain__DATA_jianshu
/nlp_group/liupeng15/code/querysim/src/corpus_process/export/data.csharp128k_data_ratio1_complete.merge/Domain__DATA_csdn__zh
/nlp_group/liupeng15/code/querysim/src/corpus_process/export/data.csharp128k_data_ratio1_complete.merge/Domain__DATA_csdn__en
/nlp_group/liupeng15/code/querysim/src/corpus_process/export/data.csharp128k_data_ratio1_complete.merge/Domain__DATA_bokeyuan
/nlp_group/liupeng15/code/querysim/src/corpus_process/export/data.csharp128k_data_ratio1_complete.merge/Domain__DATA_mafengwo_gonglv
/nlp_group/liupeng15/code/querysim/src/corpus_process/export/data.csharp128k_data_ratio1_complete.merge/Domain__DATA_mafengwo_youji
/nlp_group/liupeng15/code/querysim/src/corpus_process/export/data.csharp128k_data_ratio1_complete.merge/Domain__DATA_douban_subject
/nlp_group/liupeng15/code/querysim/src/corpus_process/export/data.csharp128k_data_ratio1_complete.merge/Domain__DATA_douban_changping
/nlp_group/liupeng15/code/querysim/src/corpus_process/export/data.csharp128k_data_ratio1_complete.merge/Domain__DATA_xia_chu_fang
/nlp_group/liupeng15/code/querysim/src/corpus_process/export/data.csharp128k_data_ratio1_complete.merge/Domain__DATA_qiche_zhijia
/nlp_group/liupeng15/code/querysim/src/corpus_process/export/data.csharp128k_data_ratio1_complete.merge/Domain__DATA_boss_zhipin
/nlp_group/liupeng15/code/querysim/src/corpus_process/export/data.csharp128k_data_ratio1_2nd.merge/Domain__2nd_arxiv_latex
/nlp_group/liupeng15/code/querysim/src/corpus_process/export/data.csharp128k_data_ratio1_2nd.merge/Domain__2nd_zhihu_jianshu_csdn_latex
/nlp_group/liupeng15/code/querysim/src/corpus_process/export/data.csharp128k_data_ratio1_2nd.merge/Domain__2nd_proof-pile
/nlp_group/liupeng15/code/querysim/src/corpus_process/export/data.csharp128k_data_ratio1_2nd.merge/Domain__2nd_open-web-math
/nlp_group/liupeng15/code/querysim/src/corpus_process/export/data.csharp128k_data_ratio1_2nd.merge/Domain__2nd_mnbvc
/nlp_group/liupeng15/code/querysim/src/corpus_process/export/data.csharp128k_data_ratio1_2nd.merge/Domain__2nd_wanjuan
/nlp_group/liupeng15/code/querysim/src/corpus_process/export/data.csharp128k_data_ratio1_2nd.merge/Domain__2nd_mathpile_bigcience_openstax_libtexts
/nlp_group/liupeng15/code/querysim/src/corpus_process/export/data.csharp128k_data_ratio1_2nd.merge/Domain__wanjuan_exam
/nlp_group/liupeng15/code/querysim/src/corpus_process/export/data.csharp128k_data_ratio1_2nd.merge/Domain__afanti_exam
/nlp_group/liupeng15/code/querysim/src/corpus_process/export/data.csharp128k_data_ratio1_2nd.merge/Code__Data_github_total_star1_sortbyrepo
/nlp_group/liupeng15/code/querysim/src/corpus_process/export/translation_zhen/data_all_shuffle.txt.ids.shuf
/nlp_group/suzhenpeng/MetaDataPipeline/chatgpt-client/clean_law/law_0416.ids
/nlp_group/suzhenpeng/MetaDataPipeline/MoDS/data/stage1_train_0527/math_0528_all.ids
/nlp_group/suzhenpeng/MetaDataPipeline/MoDS/data/stage1_train_0527/code_0528_all.ids
/nlp_group/liupeng15/code/querysim/src/corpus_process/export/mmu_llm.corpus_join_cc_math_seg.merge/CC__CC_MAIN_COMPLEX_F
/nlp_group/liupeng15/code/querysim/src/corpus_process/export/mmu_llm.corpus_join_cc_math_seg.merge/CC__CC_MAIN_F
/nlp_group/liupeng15/code/querysim/src/corpus_process/export/mmu_llm.corpus_join_cc_math_seg.merge/CC__CC_MATH
/mmu_nlp_hdd/fukai07/data/train_data/for_pretrain/v0506/SFT__kwaiYii_v0506_train
/nlp_group/lianhaoran/liupeng15/corpus_process/raw_data_process/xitiji/keshuwang.json
/nlp_group/lianhaoran/liupeng15/corpus_process/raw_data_process/xitiji/khan.json
/nlp_group/baixue05/LLM_aries/pretraindata/128k_tokenize/data_afanti/Domain__afanti_train.ids
/nlp_group/lianhaoran/liupeng15/corpus_process/raw_data_process/xitiji/xuekubao.json.out.shuf.u
/nlp_group/lianhaoran/liupeng15/corpus_process/raw_data_process/xitiji/allxuekubao.clean.valid
/nlp_group/lianhaoran/liupeng15/corpus_process/raw_data_process/xitiji/github_issue.norm.without_gce
/nlp_group/liupeng15/code/querysim/src/corpus_process/export/pdf/exam_math_code_physics_chemistry_v2.json
/nlp_group/liupeng15/tohongzhi/autoMathtext.json
/mmu_nlp_hdd/chenjunmin/dataset/gpt4/leaderboard/gsm8k_rft_aligned.jsonl.ids
/mmu_nlp_hdd/chenjunmin/dataset/gpt4/leaderboard/mathwords_amps_chinese_new_epoch_0.jsonl.ids
/nlp_group/huwenping/longcontext_data/prompts/openMathInstruct.qa.text.jsonl.ids
/mmu_nlp_hdd/chenjunmin/dataset/gpt4/leaderboard/add.jsonl.ids
/mmu_nlp_hdd/chenjunmin/dataset/gpt4/leaderboard/loben_without_question_epoch_0.jsonl.ids
/nlp_group/huwenping/longcontext_data/prompts/MetaMathQA.qa.text.jsonl.ids
/nlp_group/huwenping/longcontext_data/prompts/ORCAMath.qa.text.jsonl.ids
/nlp_group/huwenping/longcontext_data/prompts/MathInstruct.qa.text.jsonl.ids
/mmu_nlp_hdd/chenjunmin/dataset/gpt4/leaderboard/merged_stack_exchange_dedup_shuffled.jsonl.ids
/nlp_group/huwenping/longcontext_data/prompts/MetaMath.text.jsonl.ids
/nlp_group/huwenping/longcontext_data/prompts/Math_amp_with_steps_flist_relative_counting_and_statistics.qa.text.jsonl.ids
/nlp_group/huwenping/longcontext_data/prompts/Math_amp_with_steps_flist_relative_calculus.qa.text.jsonl.ids
/nlp_group/huwenping/longcontext_data/prompts/Math_amp_with_steps_flist_relative_algebra.qa.text.jsonl.ids
/nlp_group/huwenping/longcontext_data/prompts/Math_amp_no_steps_flist_relative_number_theory.qa.text.jsonl.ids
/nlp_group/huwenping/longcontext_data/prompts/Math_amp_no_steps_flist_relative_linear_algebra.qa.text.jsonl.ids
/nlp_group/huwenping/longcontext_data/prompts/Math_amp_no_steps_flist_relative_geometry.qa.text.jsonl.ids
/nlp_group/huwenping/longcontext_data/prompts/Math_amp_no_steps_flist_relative_counting_and_statistics.qa.text.jsonl.ids
/nlp_group/huwenping/longcontext_data/prompts/Math_amp_no_steps_flist_relative_calculus.qa.text.jsonl.ids
/nlp_group/huwenping/longcontext_data/prompts/Math_amp_no_steps_flist_relative_algebra.qa.text.jsonl.ids
/nlp_group/huwenping/longcontext_data/prompts/Math_amp_khan.qa.text.jsonl.ids
/nlp_group/huwenping/longcontext_data/prompts/mathplus.qa.text.jsonl.ids
/nlp_group/huwenping/longcontext_data/prompts/leetcode.qa.text.jsonl.ids
/nlp_group/huwenping/longcontext_data/prompts/Tested-143k-Python-Alpaca.qa.text.jsonl.ids
/nlp_group/huwenping/longcontext_data/prompts/codefeedback.qa.text.jsonl.ids
/nlp_group/huwenping/longcontext_data/prompts/magicoder.qa.text.jsonl.ids
/nlp_group/huwenping/longcontext_data/prompts/arc.qa.text.jsonl.ids
/nlp_group/huwenping/longcontext_data/prompts/piqa.qa.text.jsonl.ids
/mmu_nlp_hdd/chenjunmin/dataset/gpt4/leaderboard/afanti_keeptable_shuffled_text.jsonl.ids
/mmu_nlp_hdd/chenjunmin/dataset/gpt4/leaderboard/wiki_data_0829_shuffled.jsonl.ids
/mmu_nlp_hdd/chenjunmin/dataset/gpt4/leaderboard/cleaned_high_merged.jsonl.ids
/mmu_nlp_hdd/chenjunmin/dataset/gpt4/leaderboard/merged_qa.json_passd.jsonl.ids
/mmu_nlp_hdd/chenjunmin/dataset/gpt4/leaderboard/mmlu_trainval_craw_en_3+5+10_sports.ids
/mmu_nlp_hdd/chenjunmin/dataset/gpt4/leaderboard/book_matched_merged.jsonl.ids
/mmu_nlp_hdd/chenjunmin/dataset/gpt4/leaderboard/medqa_textbook_filtered_en.jsonl.ids
/mmu_nlp_hdd/chenjunmin/dataset/gpt4/leaderboard/ceval_v2v3_jikaoti0_6_mba_med_findlaw_0801.ids
/mmu_nlp_hdd/chenjunmin/dataset/gpt4/leaderboard/medqa_textbook_filtered_zh.jsonl.ids
/nlp_group/huwenping/longcontext_data/prompts/lang_und_gen_benchmarks.text.jsonl.ids
/mmu_nlp_hdd/chenjunmin/dataset/gpt4/leaderboard/ceval_correct.ids
/mmu_nlp_hdd/chenjunmin/dataset/gpt4/leaderboard/cmmlu_correct.ids
/mmu_nlp_hdd/chenjunmin/dataset/gpt4/leaderboard/mmlu_correct.ids
)

root_dir=/nlp_group/baixue05/LLM_aries/pretraindata/128k_tokenize/lang_detect_res
for infile in ${multi_files[@]}; do
    out_file_name=$(echo $infile | awk -F'/' '{print $NF}') 
    outfile=${root_dir}/${out_file_name}.lang
    python language_detect.py $infile $outfile & 
done
wait